### ISSUE TITLE
"cut" and "cp -T" commands does not exist for MacOS

### ISSUE THREAD

**Issue by mervebduman** [theislab/bartseq-pipeline#4]
Hello,

Thank you for your prompt reply for the other issue I opened. I couldn't solve my problem but I realised it might be connected with those commands that are not exist for MacOS. "cp -T" command in "rule seqs_universal" and "rule seqs_by_lib"; "cut" command in "rule map_reads". The error I get is:

``cut: illegal option -- -
usage: cut -b list [-n] [file ...]
       cut -c list [file ...]
       cut -f list [-s] [-w | -d delim] [file ...]``

and it is a similar error for the "cp -T" command.

Therefore, I altered them as below:

cp -T:
`shell:  'cp -R {input:q} {output:q}'`

cut:
I installed gcutils and altered the "cut" command as "gcut". It did not work. 
Then I tried:
`cut -f 3,10 --output-delimiter='\t' > {output.map:q}`
it also did not work.

(By the way, it was the same with "zcat". I installed coreutils and used "gzcat" and it works.)

Now my error is the same as the one before and it says: "(ERR): hisat2-align died with signal 13 (PIPE)". 

Unfortunately, I am not experienced, and I could not understand the solution you referred before. I don't know how to run the code on bash without giving the input files. And, I tried --printshellcmds tag, but it didn't show anything new; or I couldn't apply it correctly. I have a feeling that it is because of the inoperative "cut" command instead of a RAM issue.

As a note: I use Macbook Pro M1 2020 and I assume it has enough RAM power to run this. I tried "snakemake --cores" all but did not work.

Thank you very much for your time. 
Best regards,
Merve

**Comment by flying-sheep** [comment]
Thank you! So let’s talk about how we can fix those:

- `cp -T, --no-target-directory: treat DEST as a normal file`

  I used this as a safety feature: If the output exists but unexpectedly is a directory, it’ll break loudly and clearly instead of by copying things into the wrong location. `-R, -r, --recursive` is therefore exactly the opposite of what we want.

  A fix could therefore be to use [`shutil.copyfile`](https://docs.python.org/3/library/shutil.html#shutil.copyfile).

- `cut --output-delimiter`

  This is of course also necessary, maybe it could be replaced with some POSIX awk script?

- >hisat2-align died with signal 13

  Others say this indicates a resource error like out of memory: https://github.com/FelixKrueger/Bismark/issues/65#issuecomment-252091661

  I think it might also be a case of some later process in the pipe crashing.

**Comment by mervebduman** [comment]
`shutil.copyfile` helped with the cp error. For the cut, I did not change anything and it did not give any errors.

Then it gave this error:

`MissingOutputException in line 192 of /Users/mervebduman/bartseq-pipeline/Snakefile:
Job Missing files after 5 seconds:
process/1-index/amplicons/R1_001_S0.fa
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 0 completed successfully, but some output files are missing. 0
Exiting because a job execution failed. Look above for error message`

Therefore, I set the --latency-wait to 99999999. After that, I did not give any errors at all, but it was running for 4 hours without any progress. Here, I am attaching my log file.

[2022-01-27T141816.765392.snakemake.log](https://github.com/theislab/bartseq-pipeline/files/7952461/2022-01-27T141816.765392.snakemake.log)

Moreover, when I tried to run it again, it was stuck even before that job. Do you have any idea?

**Comment by mervebduman** [comment]
Thanks a lot! `shutil.copyfile` did the job. This is how it looks like:

"run:
........input = str(input)
........output = str(output) 
........shutil.copyfile(input,output)"

And, I had to import os and shutil in the beginning of the file.

For the `cut --output-delimiter` , I tried to install coreutils and `gcut` , and it worked! 

After all, I don't get the "hisat2-align died with signal 13" error.

Now, pipeline works smoothly until 85% and gives this error:

> ```
> Error in rule plot_counts_lib:
>     jobid: 0
>     output: out/counts/one/R1_001_S0/R1_001_S0-log.png
> 
> RuleException:
> PlotnineError in line 362 of /Users/mervebduman/bartseq-pipeline/Snakefile:
> "Could not evaluate the 'fill' mapping: 'log(Count)' (original error: loop of ufunc does not support argument 0 of type float which has no callable log method)"
>   File "/Users/mervebduman/bartseq-pipeline/Snakefile", line 362, in __rule_plot_counts_lib
>   File "/Users/mervebduman/opt/anaconda3/envs/snakemake/lib/python3.10/site-packages/plotnine/ggplot.py", line 727, in save
>   File "/Users/mervebduman/opt/anaconda3/envs/snakemake/lib/python3.10/site-packages/plotnine/ggplot.py", line 205, in draw
>   File "/Users/mervebduman/opt/anaconda3/envs/snakemake/lib/python3.10/site-packages/plotnine/ggplot.py", line 289, in _build
>   File "/Users/mervebduman/opt/anaconda3/envs/snakemake/lib/python3.10/site-packages/plotnine/layer.py", line 69, in compute_aesthetics
>   File "/Users/mervebduman/opt/anaconda3/envs/snakemake/lib/python3.10/site-packages/plotnine/layer.py", line 301, in compute_aesthetics
>   File "/Users/mervebduman/opt/anaconda3/envs/snakemake/lib/python3.10/site-packages/plotnine/mapping/evaluation.py", line 219, in evaluate
>   File "/Users/mervebduman/opt/anaconda3/envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
> Exiting because a job execution failed. Look above for error message
> ```

This doesn't look like a pipeline error. I am trying to fix this now, any suggestion is greatly appreciated.

EDIT: Downgrading to python 3.6.* solved my ggplot issue. Thank you again for your all help!

**Comment by flying-sheep** [comment]
Hmm, maybe R1_001_S0 has only a single cell or so. You can use snakemake’s `-k` option to create all other plots even if one fails. Everything else should already be there.
